//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Kay.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IKayListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
public partial class KayBaseListener : IKayListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycle([NotNull] KayParser.CycleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.cycle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycle([NotNull] KayParser.CycleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleDefinition([NotNull] KayParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.simpleDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleDefinition([NotNull] KayParser.SimpleDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] KayParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] KayParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] KayParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] KayParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetLiteral([NotNull] KayParser.SetLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.setLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetLiteral([NotNull] KayParser.SetLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotationLiteral([NotNull] KayParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.quotationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotationLiteral([NotNull] KayParser.QuotationLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicSymbol([NotNull] KayParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.atomicSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicSymbol([NotNull] KayParser.AtomicSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanConstant([NotNull] KayParser.BooleanConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.booleanConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanConstant([NotNull] KayParser.BooleanConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerConstant([NotNull] KayParser.IntegerConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.integerConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerConstant([NotNull] KayParser.IntegerConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatConstant([NotNull] KayParser.FloatConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.floatConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatConstant([NotNull] KayParser.FloatConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacterConstant([NotNull] KayParser.CharacterConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.characterConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacterConstant([NotNull] KayParser.CharacterConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringConstant([NotNull] KayParser.StringConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringConstant([NotNull] KayParser.StringConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
